### ISSUE TITLE
Tor Mode enabled wallet

### ISSUE THREAD

**Issue by satindergrewal** [Meshbits/pirate-chain-ios-wallet#17]
The use-case I have in my mind as of current Pirate Wallet project is, if we could have a "Tor Mode" for Pirate Wallet in settings, which if enabled, makes the wallet restart, and connect it's connections to the endpoint (in current case `lightd.meshbits.io:9067`) routed through Tor.

I know there are limitations of applying Tor routing on iOS, and I have been looking for solution to implement Tor on iOS apps for a while. But, if [Tor.framework](https://github.com/iCepa/Tor.framework) can solve what I want to achieve, having the Tor router embedded within the app will be very good to have.

These are the relevant links to read on that subject:
- https://blog.torproject.org/tor-heart-onion-browser-and-more-ios-tor
- https://github.com/iCepa/Tor.framework
- https://github.com/ursachec/CPAProxy

### More Decentralised `lightwaleltd` nodes
Because I can make a home server software coded in `golang`, which can be all in one easy to manage `Tor` node with **Pirate Chain full blockchain node** installed along with `lightwalletd` setup properly, with the **onion v3 address** setup to make a connection to the wallet.

**_In such home server setup, I can show a QR code of the onion v3 address, which the wallet can scan and add it to it's own custom `lightwalletd` servers list._**

### This will help make few things great:
- More network nodes will pop up on the network due to this feature, which helps build stronger network consensus in blockchain.
- Less reliance on my own `lightwalletd` server which can possibly be under heavy traffic if this wallet gets used heavily, or in general this same `lightwalletd` server gets used by other applications around.
- Users gets their very own exclusive server, so, they can be assure of their own privacy as equally as a they feel with full nodes.

**Overall having the ability for wallet to connect via Tor is all positive.** But if we should target this feature, we should target it only for phase 3.

### Todo tasks

- [ ] Make a mock up or basic app to ensure what we want to achieve is doable. Make a simple `Swift` coded app using `Tor.framework` `Objective-C` compiled library.
- [ ] Make a connection to `lightwalletd` gRPC server through Tor routed network over to server example `lightd.meshbits.io:9067`.
- [ ] Make a connection to `lightwalletd` gRPC server through Tor routed network over to [onion v3 address] which will be made available soon enough once we start working on this task.
- [ ] Once above testing is complete, impliment the same to Pirate Wallet(s).
